apiVersion: v1
kind: ConfigMap

metadata:
  name: fluent-bit-config
  namespace: logging

data:

  fluent-bit.conf: |

    [SERVICE]
        Flush        5
        Log_Level    info

    [INPUT]
        Name         tail
        Path         /var/log/containers/*.log
        Parser       cri
        Tag          kube.*

    [FILTER]
        Name         kubernetes
        Match        kube.*
        Merge_Log    On
        Keep_Log     Off

    [OUTPUT]
        Name         forward
        Match        kube.*
        Host         logstash
        Port         5044