apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: todo-app-secret
  namespace: prod

spec:

  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: todo-app-secret

    creationPolicy: Owner

  data:

    - secretKey: DATABASE_URL

      remoteRef:
        key: todo-app/prod
        property: DATABASE_URL