apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "backend.fullname" . }}

  labels:
    app: backend

spec:
  replicas: {{ .Values.replicaCount }}

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      serviceAccountName: {{ include "backend.serviceAccountName" . }}

      securityContext:
        runAsNonRoot: true

      containers:

        - name: backend

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          securityContext:
            allowPrivilegeEscalation: false

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          envFrom:
            - configMapRef:
                name: {{ include "backend.fullname" . }}-config

          startupProbe:
            httpGet:
              path: /docs
              port: 8000
            failureThreshold: 30
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20